
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb  5 2026 16:34:51 IST (Feb  5 2026 11:04:51 UTC)

// Verification Directory fv/top 

module top(clk, cs, we, addr, din, dout);
  input clk, cs, we;
  input [6:0] addr;
  input [31:0] din;
  output [31:0] dout;
  wire clk, cs, we;
  wire [6:0] addr;
  wire [31:0] din;
  wire [31:0] dout;
  wire n_1, n_2;
  ram_128x16A u_mem_ram_hi(.CLK (clk), .CEN (n_2), .OEN (1'b0), .WEN
       (n_1), .A (addr), .D (din[31:16]), .Q (dout[31:16]));
  ram_128x16A u_mem_ram_lo(.CLK (clk), .CEN (n_2), .OEN (1'b0), .WEN
       (n_1), .A (addr), .D (din[15:0]), .Q (dout[15:0]));
  INVX1 g3(.A (cs), .Y (n_2));
  INVX1 g4(.A (we), .Y (n_1));
endmodule

